/**
 * Style Dictionary config — Figma → code token pipeline (build plan §2).
 * Source of truth: tokens/*.json, values pulled from the Foodie App Design
 * System Figma file's Foundations page (Primitives + Semantic color, Spacing,
 * Radius, Typography, Shadow).
 */

/** Builds a nested object from a token's path segments (minus the leading category key). */
function setNested(root, path, value) {
  let node = root;
  for (let i = 0; i < path.length - 1; i++) {
    const key = path[i];
    node[key] = node[key] || {};
    node = node[key];
  }
  node[path[path.length - 1]] = value;
  return root;
}

/** Custom format: emits a TS module shaped like a Tailwind `theme.extend` object. */
function tailwindThemeFormat({ dictionary }) {
  const colors = {};
  const spacing = {};
  const borderRadius = {};
  const boxShadow = {};

  for (const token of dictionary.allTokens) {
    const [category, ...rest] = token.path;
    if (category === "color") setNested(colors, rest, token.value);
    else if (category === "spacing") setNested(spacing, rest, token.value);
    else if (category === "radius") setNested(borderRadius, rest, token.value);
    else if (category === "shadow") setNested(boxShadow, rest, token.value);
  }

  return `// Auto-generated by Style Dictionary from Figma tokens. Do not edit directly.
// Source: packages/tokens/tokens/*.json (build plan §2)

export const theme = ${JSON.stringify(
    { colors, spacing, borderRadius, boxShadow },
    null,
    2
  )} as const;
`;
}

module.exports = {
  hooks: {
    formats: {
      "custom/tailwind-theme": tailwindThemeFormat,
    },
  },
  source: ["tokens/**/*.json"],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "dist/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: { selector: ":root" },
        },
      ],
    },
    js: {
      transformGroup: "js",
      buildPath: "src/generated/",
      files: [
        {
          destination: "tokens.generated.ts",
          format: "javascript/es6",
        },
      ],
    },
    tailwind: {
      transformGroup: "js",
      buildPath: "src/generated/",
      files: [
        {
          destination: "tailwind-theme.generated.ts",
          format: "custom/tailwind-theme",
        },
      ],
    },
  },
};
